// Icon mapping for Lucide React Native
export const iconNames = {
  target: 'target',
  wallet: 'wallet',
  piggyBank: 'piggy-bank',
  dumbbell: 'dumbbell',
  heart: 'heart',
  book: 'book',
  flame: 'flame',
  trophy: 'trophy',
  mountain: 'mountain',
  plant: 'sprout',
  glass: 'glass-water',
  runner: 'user',
  folder: 'folder',
  menu: 'menu',
  plus: 'plus',
  check: 'check',
  x: 'x',
  edit: 'edit',
  trash: 'trash',
  settings: 'settings',
  calendar: 'calendar',
  clock: 'clock',
  checkCircle: 'check-circle',
  circle: 'circle',
  arrowLeft: 'arrow-left',
  arrowRight: 'arrow-right',
  search: 'search',
  filter: 'filter',
  sliders: 'sliders-horizontal',
} as const;

export type IconName = typeof iconNames[keyof typeof iconNames];
